---
title: "BeerSales"
author: "Justin Howard, Amber Burnet"
date: "June 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir ='C:/Users/howar/Documents/doingdatascience/BeerSales')
```
## Loading the beer data:
```{r loading beer data}
file1<- 'C:/Users/howar/Documents/R__working_directory/DDS/msds-6306-doing-data-science/Unit 7/Beers.csv'
Beers<- read.csv(file1)
str(Beers)
head(Beers)
```
## Loading the brewery data:
```{r loading brewiery data}
file2<- 'C:/Users/howar/Documents/R__working_directory/DDS/msds-6306-doing-data-science/Unit 7/Breweries.csv'
Breweries<- read.csv(file2)
str(Breweries)
head(Breweries)
```
## Merging the two datasets on "Brewery_id"
```{r merging dataset}
names(Breweries)<- c("Brewery_id", "Brewery_Name", "City", "State")
BeerNBrew<- merge(Beers, Breweries, by = "Brewery_id")
head(BeerNBrew)
tail(BeerNBrew)
```
## Counting the number of NA values per column:
```{r NA counts}
na_count<- sapply(BeerNBrew, function(x) sum(is.na(x)))
na_count<- data.frame(na_count)
na_count
```  
#### Observations:
2 columns contain large numbers of NA values: 
ABV - 62
IBU - 1005

## How many breweries are in each state?
```{r aggregating, warning=F}
library(dplyr)
bystate<- BeerNBrew %>%
  group_by(State) %>%
  distinct(Brewery_id)
  
head(bystate)
brewcount<- aggregate(Brewery_id ~ State, BeerNBrew, length)

names(brewcount)<- c("State", "Brewery_Count")
brewcount
```
## Median alcohol content and international bitterness unit for each state.
```{r aggregating medians - IBU}
IBUvals<- BeerNBrew %>%
  group_by(State) %>%
  filter(!is.na(IBU))
head(IBUvals)

IBUmedians<- aggregate(IBU ~ State, IBUvals, median)
names(IBUmedians)<- c("State", "Median_IBU")
head(IBUmedians)
```

```{r aggregating medians - alcohol content}
boozecontent<- BeerNBrew %>%
  group_by(State)
boozemedians<- aggregate(ABV ~ State, boozecontent, median)
names(boozemedians)<- c("State", "Median_ABV")
boozemedians
```
### Bar Charts 
```{r plotting the medians}
library(ggplot2)
ggplot(IBUmedians, aes(x=State, y=Median_IBU, fill=State)) + geom_bar(stat= 'identity')
ggplot(boozemedians, aes(x=State, y=Median_ABV, fill=State)) + geom_bar(stat= 'identity')
```
